version: "3.9"  # optional since v1.27.0
services:
   db:
     image: mysql:5.6
     container_name: db
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: samplepass
       MYSQL_DATABASE: sample
       MYSQL_USER: sampleuser
       MYSQL_PASSWORD: samplepass
     networks:
      LAN:
        ipv4_address: 172.23.17.10

   apachephp:
     depends_on:
       - db
     image: php:7.3-apache
     container_name: docker-php
     ports:
       - "80:80"
       - "443:443"
     environment:
       DB_HOST: db:3306
       DB_USER: sampleuser
       DB_PASSWORD: samplepass
       DB_NAME: sample
     networks:
      LAN:
        ipv4_address: 172.23.17.20

volumes:
    db_data: {}

networks:
  LAN:
    driver: bridge
    ipam:
      config:
      - subnet: 172.23.17.0/24
